version: '3.8'

# containers => services
services:
  crm:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/crm
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=crm
      - MYSQL_PASSWORD=crm
      - MYSQL_DATABASE=crm
volumes:
  mysql_data:
  mysql_config:

 